exchange:
  app_id: aefbfee9111d4ffa866d19e8e695f70d
  base_currency: USD
  base_url: https://openexchangerates.org/api
  currencies_path: /currencies.json
  latest_path: /latest.json
  historical_path: /historical
giphy:
  api_key: atuucIf27VBVBPx2AdhTQWzLq66EZzBC
  base_url: api.giphy.com/v1/gifs/random
  positive_tag: rich
  negative_tag: broke